[build]
target = "./index.html"

[watch]
ignore = ["./src-tauri"]

[serve]
addresses = ["127.0.0.1","::1","10.86.180.226","0.0.0.0"]
# addresses = ["0.0.0.0"]
port = 1420
open = false
ws_protocol = "ws"